### ISSUE TITLE
Issue when creating folders concurrently

### ISSUE THREAD

**Issue by Toflar** [contao/core-bundle#1018]
There are issues when two (or more) users create a new folder at the same time.
How to reproduce:

* Open file manager in Browser A
* Click on "New folder"
* Choose the root folder directly as a target
* Open file manager in Browser B
* Click on "New folder"
* Choose the root folder directly as a target
* Switch back to Browser A, enter a folder name and hit "save and back"
* First exception: `"Failed to remove directory "[...]web/files": .`
* Switch back to Browser B, enter a folder name and hit "save and back"
* Second exception: `File or folder "files/__new__" is not mounted or cannot be found.`

**Comment by leofeyer** [comment]
I assume this only happens if the root folder is the target, right?

**Comment by Toflar** [comment]
No, the second exception in Browser B also occurs in a subfolder `test`: `File or folder "files/test/__new__" is not mounted or cannot be found.`

**Comment by leofeyer** [comment]
I was not able to reproduce the first exception ("failed to remove directory …") but I was able to reproduce the second. Here is what happens:

* You click on "new folder" and select a target -> the folder `files/__new__` is generated.
* You enter a name and `files/__new__` is renamed to `files/name`.
* At this time, the other tab still expects a folder `files/__new__` to exists, which however does not, because it has been renamed to `files/name`.

So I guess you cannot add new folders into the same directory in multiple tabs concurrently.

**Comment by CMSworker** [comment]
Is this issue solved (because it got closed)? If not, just a thought: It might be a simple solution to just add a random number or a random hex-code to the temporary name of the newly created folder here:

https://github.com/contao/core-bundle/blob/08a6a6c9eab3669e8ae96deb1ea95dba9ebf2ebf/src/Resources/contao/drivers/DC_Folder.php#L565

and here:

https://github.com/contao/core-bundle/blob/08a6a6c9eab3669e8ae96deb1ea95dba9ebf2ebf/src/Resources/contao/drivers/DC_Folder.php#L566

Example: When creating a new folder in tab A it's called `/files/__new_345a4c__/`, in tab B `/files/__new_ee67f8__/` etc so it would be less likely to be overwritten from within another tab...

**Comment by leofeyer** [comment]
If you search for `__new__` in the code, you will find a lot more occurrences than just the two you have mentioned. I agree that it might be solvable this way, but is this not just an edge case?
