### ISSUE TITLE
cant find Route contao/install 

### ISSUE THREAD

**Issue by easycalib-git** [contao/core-bundle#1364]
Hi:
i hope you can help me,
after installing core-bundle 4.5.3 on my Symfony 3.4 applications, and followed all the instructions given in the main page, i am unable to access the route contoa/install, i checked the debug routes, and it doenst show up
![image](https://user-images.githubusercontent.com/33333099/36077917-c0c60fd2-0f70-11e8-972a-53b0d535bc26.png)

**Comment by fritzmg** [comment]
You also need the contao/installation-bundle

**Comment by aschempp** [comment]
If you want to use the install tool, you need to add the installation-bundle. Otherwise you can update the database using the Doctrine command or add Doctrine Migrations to your application. The Contao database changes are added to the Doctrine Schema tool (even though we're not actually using Doctrine entities).

**Comment by bytehead** [comment]
This should be mentioned as installation/configuration optionin the `README.md`.
