### ISSUE TITLE
Encryption class -> shouldn't the implementation be in the core?

### ISSUE THREAD

**Issue by Defcon0** [contao/core-bundle#1380]
Hello,

since Contao 3.5 the Encryption class is deprecated and one shouldn't use it anymore.

Shouldn't there be an alternative implementation for that since for example ModuleRegistration uses it? How are the plans for that? I could do a pull request for that I guess. Is there a need for that or will it be thrown out of the core completely?

Bye Defcon0

**Comment by Toflar** [comment]
There's no such thing as "one encryption algorithm fits all". Our old `Encryption` class uses deprecated and unsafe `mcrypt` stuff that has been removed from PHP core in 7.2. The class itself is not used anywhere in the core. `ModuleRegistration` just supports the `eval` attribute as in the back end DCA. So yes, it will be removed completely from core because encryption should be left to professional libraries and implemented for specific purposes.

**Comment by fritzmg** [comment]
> The class itself is not used anywhere in the core

The class is used in `Contao\ModuleRegistration`, both in Contao 3.x and 4.x.

**Comment by Toflar** [comment]
Yes, the core doesn't use it. No field has `eval->encrypt` set to `true`.

**Comment by fritzmg** [comment]
Ah ok, got it, you meant the `eval` setting is not used by the core :).

**Comment by Defcon0** [comment]
@Toflar Is right, password_hash is used for password hashing, no encryption.

Hence I'll write a simple encryption for our https://github.com/heimrichhannot/contao-utils-bundle using the contao secret.

**Comment by Toflar** [comment]
> Hence I'll write a simple encryption

Please, don't do that. Writing your own encryption algorithm is always wrong unless you are a mathematician and specify in cryptography. Just use simple load and save callbacks together with phpseclib and you're fine.

**Comment by Defcon0** [comment]
You got me wrong ;-) Of course, I won't write a custom encryption. The plan was to use php's openssl extension in order to do that in combination with – as you mentioned – load and save callback ;)
