### ISSUE TITLE
Problem with script tag in allowed HTML tags / settings

### ISSUE THREAD

**Issue by stefansl** [contao/core-bundle#1405]
I'm adding <script> to allowed HTML tags right at the beginning of the string
![bildschirmfoto1 min](https://user-images.githubusercontent.com/1564251/36815384-d3c4dd6c-1cda-11e8-89a2-8e029234eee7.png)

In the system log appears a table (Contao 4.4.14 / 4.5.4)
![bildschirmfoto 2018-02-28 um 22 58 54 min](https://user-images.githubusercontent.com/1564251/36815440-fc4f760c-1cda-11e8-92d0-09f669eb04da.png)

If I put <script> right behind a - the a tag will be removed. (Contao 4.4.14 / 4.5.4)

**Comment by stefansl** [comment]
ok, the first issue seems to be an issue of https://github.com/OMOSde/contao-om-backend/issues/26

**Comment by leofeyer** [comment]
So what is the issue here now?

**Comment by stefansl** [comment]
> If I put <script> right behind a - the a tag will be removed. (Contao 4.4.14 / 4.5.4)

**Comment by leofeyer** [comment]
That's because this regex matches `<a><script>`:

https://github.com/contao/core-bundle/blob/15806d3c5fcb19f3c329806c25bb8180359f5265/src/Resources/contao/library/Contao/Input.php#L618

@ausi The regex is supposed to match `<script>` tags inside `<a>` tags, not subsequent ones. Do you think it is safe to replace `[^a-z]` with `[^a-z>]`?

**Comment by ausi** [comment]
> Do you think it is safe to replace `[^a-z]` with `[^a-z>]`?

Yes should be safe I think.
But maybe we should also use the raw input for the allowed HTML tags field?

**Comment by leofeyer** [comment]
That's a much better idea. 👍

**Comment by leofeyer** [comment]
Fixed in 1809ac78cd99ae90256fb21acc8bdacd0c4392d5.
