### ISSUE TITLE
SEO: Make Frontend-Breadcrumb accessible for Google

### ISSUE THREAD

**Issue by Xendiadyon** [contao/core-bundle#1421]
In the Frontend-Breadcrumb navigation, the BreadcrumbList-Schema is used, which is perfectly fine.
But: Google does never generate a Breadcrumb-Path in the search results for our pages.
We think that the whole issue is complicated as soon as we are using https.

This Contao page does not generate a "breadcrumb-able" search result:
![image](https://user-images.githubusercontent.com/2657385/37274292-7a8dace6-25dc-11e8-9d97-fb4eb6aaf6b9.png)

But it is obviously possible to make Google generate a breadcrumb, even when using https. Let me just show you a generic example page:
![image](https://user-images.githubusercontent.com/2657385/37273610-a2f0a83e-25da-11e8-80f7-f525bb0decc8.png)

Code:
![image](https://user-images.githubusercontent.com/2657385/37273724-ee938856-25da-11e8-9ca4-db89f8d8c419.png)

Do you have experience how we could bring Google to parse/implement our breadcrumb menus to the Google search results?

Do we explicitely need use use itemprop="breadcrumb"? Or is the type="v:Breadcrumb" the catcher? Is an ol instead of ul neccessary?

Literature:
https://www.trustagents.de/wissen/breadcrumb
In Fact, Google recognizes our BreadcrumbList:
https://search.google.com/structured-data/testing-tool/

**Comment by fritzmg** [comment]
See also https://developers.google.com/search/docs/data-types/breadcrumb

**Comment by CMSworker** [comment]
> We think that the whole issue is complicated as soon as we are using https

No, it's not related to HTTPS. The only difference is that Google doesn't show a short name for the Website as first breadcrumb path element, but instead the URL to indicate that it has HTTPS:

Example without https:
`Contao Official Demo > Content Elements > Content slider`

Example with https would look like:
`https://demo.contao.org > Content Elements > Content slider`

> Do we explicitely need use use itemprop="breadcrumb"? Or is the type="v:Breadcrumb" the catcher?

No, your example from the shopping website is using the older http://www.data-vocabulary.org – this service ended in 2011 and today it's recommended to use https://schema.org – The old vocabulary is only required if you want to try to bring breadcrumbs also to bing.com because Microsoft is slow and didn't switch from data-vocabulary.org to schema.org yet (at least not completly). Related infos in this link: https://stackoverflow.com/questions/45494059/breadcrumb-microdata-markup-valid-both-for-google-and-bing

> Is an ol instead of ul neccessary?

`<ol>` is recommended and used in the examples by Google (see link from @fritzmg) and also semantically correct, because the path has an order `1 > 2 > 3` to indicate the depth or nesting levels - So you should use an ordered list.

I made some testing with Contao, microdata and Google last year and those were my findings related to breadcrumbs:

1) The microdata structure of the current Contao breadcrumb template is incomplete. Please compare the two example snippets to see the difference:

Currently with the Contao default breadcrumb template:
```
<li itemscope itemtype="http://schema.org/ListItem" itemprop="itemListElement">
  <a href="en/content-elements.html" title="Content Elements" itemprop="url">
    <span itemprop="name">Content Elements</span>
  </a>
</li>
```
This would be the correct way:
```
<li itemscope="" itemprop="itemListElement" itemtype="http://schema.org/ListItem" >
  <span itemprop="item" itemscope="" itemtype="http://schema.org/Thing">
    <a href="https://demo.contao.org/en/content-elements.html" itemprop="url">
      <span itemprop="name">Content Elements</span>
    </a>
  </span>
  <meta itemprop="position" content="1" />
</li>
```
- the wrapping `<span>` element has to be added with itemtype thing, the url and name belong to this thing, not to the list item
- the itemprop position with an number has to be added

This looks weird but follows the structuring rules of microdata. Also all microdata breadcrumb examples from Google are structured like this.

2) **The first link to the homepage should not be marked as part of the Microdate breadcrumb list.** At least in my testings this ended up showing the URL and Website name twice in the Google search result breadcrump, for example like this:

`https://demo.contao.org > Contao Official Demo > Content Elements > Content Slider`

I also noticed, that in the examples from Google the first breadcrumb is never a domain name. The first breadcrumb path is the category. This brings me to the next finding:

3) Google seems to ignore the breadcrumb path for pages without subpages. The breadcrumb path will only be shown when there are at least 2 nesting levels (at least in my testings).

4) Please also note, that changes in the breadcrumb structure are verly slowly recocnized/indexed by Google. You can force an crawling update in the Google Webmaster Tools, but it will still need some days/weeks to see the changes in the search results...

Is a pull request to update the mod_breadcrumb template welcome?

**Comment by leofeyer** [comment]
Definitely.

**Comment by fritzmg** [comment]
Such a change to the breadcrumb template would break backwards compatibility though.

**Comment by leofeyer** [comment]
There is no BC promise for templates.

**Comment by fritzmg** [comment]
> There is no BC promise for templates.

According to your comment [here](https://github.com/contao/core/issues/6731#issuecomment-37388753) there is ;).

**Comment by leofeyer** [comment]
This comment is 4 years old. We have made a lot of conceptual changes since then.

**Comment by fritzmg** [comment]
I see, then I am all for this change as well of course.

Is it documented somewhere, what constitutes a BC and what isn't?

**Comment by CMSworker** [comment]
See #1429 with an temporarily long commented php version. This would be the "basic" change I suggest.

I'm not so familiar with the coding style used in the Contao templates with the mixed html and php and hope I adapted the php code correctly to this style.

Feedback welcome

**Comment by leofeyer** [comment]
See #1429.
