### ISSUE TITLE
Referrer management broken

### ISSUE THREAD

**Issue by importer** [contao/core-bundle#143]
> <a href="https://github.com/leofeyer"><img src="https://avatars.githubusercontent.com/u/1192057?v=3" align="left" width="42" height="42" hspace="10"></img></a> [Issue](https://github.com/contao/contao/issues/65) by @leofeyer
Monday Mar 09, 2015 at 18:49 GMT

Somewhere along the way we broke the referrer management in the back end. Steps to reproduce:

- Log into the back end.
- Open the article module.
- Open any article for editing.
- Edit any content element.
- Click on the "back" button.

It keeps sending me to the welcome screen.

**Comment by Toflar** [comment]
This one can be closed in favor of #207.

**Comment by leofeyer** [comment]
There is still a little problem with the referer URLs:

1. Log into the back end.
2. Open the articles module.
3. Open an article for editing.
4. Open a content element for editing.
5. Click on the "back" button (correctly takes you back to the article).
6. Click on the "back" button of the article (takes you to the home page instead of the article listing).

@Toflar Can you please check if this is a bug in the new session listeners?

**Comment by aschempp** [comment]
@leofeyer please also try this in the Demo, I'm pretty sure that problem always existed…

**Comment by leofeyer** [comment]
I did try it in the demo and it works in Contao 3. Otherwise I would not have reopened the ticket.

**Comment by leofeyer** [comment]
Fixed in b1794950629cd8e2a953d12c3fadf88732008f01.
