### ISSUE TITLE
first back end login attempt sometimes fails

### ISSUE THREAD

**Issue by fritzmg** [contao/core-bundle#1431]
Reproduction:

1. Delete all cookies for demo.contao.org in your browser.
2. Restart your browser.
3. Go to https://demo.contao.org/contao.
4. Click "Continue".

The login will fail.

However, I cannot reproduce this consistently. In Chrome for example I am often redirected to the front end instead for some reason.

**Comment by leofeyer** [comment]
I have stumbled across this as well and I believe it has something to do with the request token now being a double submit cookie. @ausi What do you think?

**Comment by fritzmg** [comment]
I also had one instance where I could not log in at all - until I manually deleted the CSRF token cookie.

**Comment by ausi** [comment]
I made a big mistake in dbc0f7bcbd6ed9d541f2e458ce20a854f68a09e9 :(

The token is actually base64, not alphanumeric. See https://github.com/symfony/security/blob/af2a98fbe320df448c73c290da669e97be00cb80/Csrf/TokenGenerator/UriSafeTokenGenerator.php#L43

We should change the regex in https://github.com/contao/core-bundle/blob/08a6a6c9eab3669e8ae96deb1ea95dba9ebf2ebf/src/EventListener/CsrfTokenCookieListener.php#L110
to `/^[a-z0-9_-]+$/i` to fix this.

The issue doesn’t occur consistently because sometimes the generated token doesn’t contain `_` or `-` in which case everything works fine.

**Comment by leofeyer** [comment]
Certainly not a big mistake. 😄

**Comment by ausi** [comment]
I created a pull request to fix this: #1434

**Comment by leofeyer** [comment]
Thank you.
