### ISSUE TITLE
4.5.7

### ISSUE THREAD

**Issue by e9li** [contao/core-bundle#1457]
After updating to 4.5.7 I have weird chars after the hidden token field in every form. Also request token is not working at all. There are no custom templates. Notification center is installed.

![contao-457](https://user-images.githubusercontent.com/1247727/38349712-9c5a1628-38a8-11e8-8d67-c32e8dfcfb16.png)

**Comment by frontendschlampe** [comment]
But in original template I can't see any problem: https://github.com/contao/core-bundle/blob/4.5/src/Resources/contao/templates/forms/form_wrapper.html5

Please have a look in ```value``` of ```<input type="hidden" name="REQUEST_TOKEN"``` ... it looks like if there's any extension or JavaScript which changes something because the```value``` for the request token is broken and ```onerror="continue"``` is not a default option. 

I tested in my installation and there's no problem.

**Comment by e9li** [comment]
The form_wrapper.html is not touched. These chars appear even when javascript is disabled, so they must be inserted in pho somewhere. I have isotope, notification center and changelanguage installed. There are no specialities with javascript or anything else. Does maybe one of these extensions manipulate the hidden request token?

**Comment by e9li** [comment]
Yes, I am using page cache, but cleared the cache several times in contao, contao-manager and even manually.

**Comment by Toflar** [comment]
I think some extension is fiddling around with the content. What happens if you uninstall all extensions?

**Comment by e9li** [comment]
Jep, found the problem, the glumanda99/contao-photoswipe extension caused the problem. Thanks for all the help!

**Comment by fritzmg** [comment]
See also https://github.com/glumanda99/contao-photoswipe/issues/6
