### ISSUE TITLE
[4.5] Unreproducible frontend auth error.

### ISSUE THREAD

**Issue by richardhj** [contao/core-bundle#1542]
### Site structure:
* Home
* Login (guest only)
* My Applications (protected)
* My Data (protected)

![screen shot 2018-06-06 at 11 55 12](https://user-images.githubusercontent.com/1284725/41031266-8d41f9cc-6980-11e8-99a0-279394cea7ff.png)

### Frontend:

**Default behaviour**: Unauthenticated User switches to "Login". User logs in. User can access the protected pages (My Applications, My Data).

**Unreproducible random behaviour**: User is logged in. User can access either page My Application or page My Data (proof of being logged in). **User cannot access the other protected page**. He then **gets redirected to the Login page**.  
**No entry** of "Page XY can only be accessed by groups ..." in the system log.  
Tried to have a look at the http response code with Chromes debug bar with "disable cache" enabled >> with cache disabled the page can be accessed.

**Comment by m-vo** [comment]
Can you give a bit more background information? Symfony version, cache settings for the pages, ...
Random behaviour is hard  to debug. Can you try to narrow the problem down - e.g. try to create a minimal version (no extensions, just the needed pages) where the problem appears.

**Comment by richardhj** [comment]
Yes, it’s me who needs to debug. 
Actually I was hoping someone has a clue or did experiencing something similar. 
I run the latest versions available. It would be a pain if it only occurs on my live system.

**Comment by christian-kolb** [comment]
I had kind of the same problem, and "fixed" it just a minute ago while trying to gather all the things I tried to debug the issue. Before the solution, here the following things I tried, as this might not be the solution for your problem. 

I have a structure of

- Homepage
- Login
- Member Area (protected)
    - Profile edit (protected / custom module)
        - Edit detail elements (protected / custom module)

When logging in, the user is redirected to the "Member Area". From there he can choose to edit his profile through the "Profile edit" page. Everything on that page works normal. Then he can switch to "Edit detail elements". I can open that page once and everything works, but as soon as I refresh that third level page (Edit detail elements), I directly get redirected to the login. Without any kind of error page or error message in any logs. The strangest part: Everything works in production mode. I only have the issue in dev mode. @richardhj Is this the same case for you?
And additionally I can access and refresh the page when removing or disabling the module.

What I tried already:

- Looking through every single line of log in the dev log file for the requests (which is > 1MB)
    - Not one error is thrown
- Used different types of session configuration
    - Different `handler_id` didn't make a difference 
- Removed all special bundles in the AppKernel for the dev environment
- Removed all special configuration for the `config_dev.yml`
- Tried different levels in the navigation
    - Last element of the navigation to the same as "Profile edit"
    - Different lengths of url
    - Used the module with auto item and without
- Cut the module down to an empty module with just a compile function. And that's the part where I found the solution : )

With the cut down module it worked, so I started adding things back one by one. In the end the following line was the issue:

```php
$GLOBALS['TL_JAVASCRIPT'][] = 'files/js/mod_member_staff_manage_edit.js';
```

But that file doesn't exit. What does exist is

```php
$GLOBALS['TL_JAVASCRIPT'][] = 'files/js/mod_member_staff_manage.js';
```

**So apparently referencing a javascript file which doesn't exist leads to a redirect to the login.**

This doesn't make sense to me. Especially because there is no logging even in debug mode of this behaviour. Is this a bug or an undocumented and unlogged feature?

@richardhj Does this help with your problem?

**Comment by richardhj** [comment]
Hi @christian-kolb 
Thanks for this giant comment.

There are a few points differing: I am in production mode (the website is online) and I don't use `$GLOBALS['TL_JAVASCRIPT']` nor `$GLOBALS['TL_CSS']` in my custom modules.
Only 2 members out of 400 that aimed to login on that day complained about the authentication errors described above. And I was able to reproduce it rarely - there ain't no systematic behaviour.

I, personally, decided to wait it out. But what is about your issue @christian-kolb. You want to figure it out more profound?

**Comment by christian-kolb** [comment]
Hi @richardhj,

yeah, sounds like something different. I opened up a separate issue for my problem here: https://github.com/contao/core-bundle/issues/1572

**Comment by leofeyer** [comment]
@richardhj Does the original issue occur in the [online demo](https://demo.contao.org/contao) as well?

**Comment by richardhj** [comment]
Closing because of poor reproducibility.
The issue has no prioritization on my side.
