### ISSUE TITLE
FileUpload: return or continue

### ISSUE THREAD

**Issue by leofeyer** [contao/core-bundle#1557]
This ticket refers to #1507.

@fritzmg Are you sure that `return $arrUploaded;` in [line 161](https://github.com/contao/core-bundle/pull/1507/files#diff-baa21854e252dcb04da2c161f324cf07R161) is correct? Since we are inside a for loop, should we not use `continue` instead?

**Comment by fritzmg** [comment]
Does `continue` work within an `if` or `else`? I didn't know 😁 

The early out is there so that [this part](https://github.com/fritzmg/core-bundle/blob/118ffbfbf8af169ca48a5313f554214427a85d2a/src/Resources/contao/classes/FileUpload.php#L165-L192) is not being executed. In case of an error, [this is reached otherwise](https://github.com/fritzmg/core-bundle/blob/118ffbfbf8af169ca48a5313f554214427a85d2a/src/Resources/contao/classes/FileUpload.php#L196).
