### ISSUE TITLE
Remove the `CombinedFileLocator` class

### ISSUE THREAD

**Issue by leofeyer** [contao/core-bundle#167]
After playing with the new locator classes, I'm no longer sure whether we need the `CombinedFileLocator` class at all. The `locate()` method is using legacy code and does not yet cover all use cases, but most important, isn't the following example of how to load a cache file what makes the most sense?

```php
$locator = new FileLocator([$container->getParameter('kernel.cache_dir') . '/contao']);

try {
    include $locator->locate('config/autoload.php', null, true);
} catch (\InvalidArgumentException $e) {
    // Load the resources one by one
}
```

What's the advantage of the `CombinedFileLocator`? And should it not have be called `CachedFileLocator` in the first place?

**Comment by leofeyer** [comment]
Here's a working POC of what I mean: 82afb43860dc617c77c53ede520ccd0ce535daef

**Comment by leofeyer** [comment]
The changed routines also make use of the `$currentPath` argument, so now the class behaves more like the original class.

**Comment by aschempp** [comment]
Your approach has several flaws. There are situations where you do not want to find the cache file, even if it exists. That's why there are two different services. For example when building the cache files, or for things like templates that cannot be cached.

You also added a new method `locateCacheFile` which is not part of the interface. Not following the interface would not work with the Chain. Also, you are mixing two separate functionalities in the same class, which is not a good idea.

The whole point of the `CombinedFileLocator` is that if you look for all `config.php` files and there is a combined version, it will only return one. If there is no combined version, it will return all files.

PS: It's called `Combined` because it loads a combination of all the files it would otherwise find. Also the sibling class is called `CombinedFileDumper` because it combines files, it does not "magically cache them".

**Comment by leofeyer** [comment]
Ok, I see the advantages of having a separate class.

> The whole point of the `CombinedFileLocator` is that if you look for all `config.php` files and there is a combined version, it will only return one. If there is no combined version, it will return all files.

Yes, but that's not what the class currently does. Look at the current code:

```php
// System::loadLanguageFiles()
try
{
	include $kernel->getContainer()->get('contao.cached_resource_locator')->locate('languages/' . $strCreateLang . '/' . $strName . '.php', null, true);
}
catch (\InvalidArgumentException $e)
{
	$objLocator = $kernel->getContainer()->get('contao.resource_locator');
	$xlfLoader  = new XliffFileLoader($kernel->getRootDir(), true);

	// XLIFF files will overwrite PHP files if both exist in the same bundle
	$arrFiles = array_merge
	(
		$objLocator->locate('languages/' . $strLanguage . '/' . $strName . '.php'),
		$objLocator->locate('languages/' . $strLanguage . '/' . $strName . '.xlf')
	);
```

In contrast to what you have said, the combined locator has not returned all files. Instead, you have been using a different service.

This is what I would expect the usage to be:

```php
$objLocator = $kernel->getContainer()->get('contao.cached_resource_locator');

try
{
	include $objLocator->locate('languages/' . $strCreateLang . '/' . $strName . '.php', null, true);
}
catch (\InvalidArgumentException $e)
{
	$xlfLoader  = new XliffFileLoader($kernel->getRootDir(), true);

	// XLIFF files will overwrite PHP files if both exist in the same bundle
	$arrFiles = array_merge
	(
		// Still using the cached_resource_locator here, but since I am not passing
		// true, it does not look for the first file and returns all files.
		$objLocator->locate('languages/' . $strLanguage . '/' . $strName . '.php'),
		$objLocator->locate('languages/' . $strLanguage . '/' . $strName . '.xlf')
	);
}

**Comment by aschempp** [comment]
Language files is a special topic, because we can't simply use the result of the combined `locate()` method, because it would return only PHP files if there is no cached version. For languages though, we want XLIFF too. That's why I'm using `$first=true` here which will throw an exception if no cached version is found (not asking the sub-locator).

Contrary, look at the DcaLoader: https://github.com/contao/core-bundle/blob/develop/src/Resources/contao/library/Contao/DcaLoader.php#L77-L80
It simply iterates over the result. If a combined version is found, the result will be an array of one file. If not, the result will be all located files.

**Comment by leofeyer** [comment]
Ok, seems I have picked the most unfavorable example :(

**Comment by leofeyer** [comment]
But the class still does not handle all cases:

https://github.com/contao/core-bundle/commit/1146a5f58b78e90d3d3bfe4c1cf1d11004c829ea#diff-d31ad2e5efd4824ecbf4654337a80103R58

**Comment by leofeyer** [comment]
See #169.
