### ISSUE TITLE
Missing commits from @discordier/feature/exception-listener

### ISSUE THREAD

**Issue by aschempp** [contao/core-bundle#201]
Commits https://github.com/discordier/core-bundle/commit/6a24bf2 and https://github.com/discordier/core-bundle/commit/f747359 have not been merged into `develop`

**Comment by leofeyer** [comment]
This is because the commits were made after I had started merging. But I have applied the changes manually, haven't I?

https://github.com/contao/core-bundle/blob/develop/src/EventListener/ExceptionListener.php#L142

https://github.com/contao/core-bundle/blob/develop/src/EventListener/ExceptionListener.php#L306-L308
