### ISSUE TITLE
Register bundles by configuration

### ISSUE THREAD

**Issue by dmolineus** [contao/core-bundle#280]
At the moment each bundle has to be added to the AppKernel manually. I'm not sure if the Contao Package Manager will provide an easy way to register the bundles automatically.

It would ease the extension installation if users don't have to care about it. Maybe adding bundles using the Symfony configuration could be a way. This is the way like the [Oro Plattform](https://github.com/orocrm/platform) solves it.

There is a `bundles` section and also an `exclusions` section. An custom AppKernel parses the configuration to register the bundles automatically.

Ressources:
- [Enable bundles in Oro Plattform documentation](http://www.orocrm.com/documentation/index/current/cookbook/how-to-create-new-bundle#enable-bundle)
- [OroKernel autoloading the bundles](http://www.orocrm.com/documentation/index/current/cookbook/how-to-create-new-bundle#enable-bundle)
- [AppKernel of a project](https://github.com/orocrm/crm-application/blob/master/app/AppKernel.php)

I don't know if you have any solutions prepared, discussed and on the roadmap. Maybe the mentioned way oro handles it could be a great solution for Contao as well.

**Comment by aschempp** [comment]
We did discuss several solutions and also implemented our own, but then removed it again for the 4.0 because we were not sure what's best. We did not know of Oro though.

Here's some of our background:
 - https://github.com/symfony/symfony/issues/9341
 - https://github.com/symfony/symfony/pull/13945
 - https://github.com/redkite-labs/BootstrapBundle
 - https://github.com/contao/core-bundle/pull/64
 - https://github.com/contao/core-bundle/tree/d842c1688a26bb9b47bcc3de1b38ef89a726c8f6/src/Autoload (not necessarily the latest version)

**Comment by leofeyer** [comment]
The biggest difference between most of the stuff (including Oro) and our former solution is that we also need dependency resolving. A simple auto-registration does not suffice.

**Comment by leofeyer** [comment]
The Contao Manager will take care of all this.
