### ISSUE TITLE
Bundle language files

### ISSUE THREAD

**Issue by aschempp** [contao/core-bundle#299]
As we all know, the current distribution of Contao 4.0 does only contain the english language files. There is a suggestion to pull translations using the transifex client. However, there are two major problems to this:

 1. most users will not be able to install the Transifex client on their hosting account
 2. files would be downloaded into the vendor folder, which should only be managed by composer.

I am therefore proposing to download the translations into the bundles and push them to the GIT repository. I can't see any drawbacks with that. We're already doing that successfully with Isotope.

**Comment by discordier** [comment]
We are doing the same for MetaModels and AFAIR @tristanlins was doing the same for Avisota.

**Comment by tristanlins** [comment]
> @tristanlins was doing the same for Avisota.

affirmative

**Comment by Toflar** [comment]
Same here. Also Symfony bundles provide their own translations in the same bundle. I know it makes a git diff harder because most of the times you don't care about language strings but we should not make it harder vor 95% of all the people to install languages just so that the other 5% of developers can git diff easily...

**Comment by leofeyer** [comment]
This has been fixed in version 4.0.2. The web-based installer allows to install a complete distribution without having to use Composer or the Transifex client. And it saves us from polluting the repo with language files (which is why we have removed them in the first place).

**Comment by aschempp** [comment]
which makes using `composer create-project` unusable?

**Comment by discordier** [comment]
Correct

**Comment by leofeyer** [comment]
It does not. `composer create-project` will still install Contao with the default translation. If you need more translations, download them with the Transifex client or install the distribution. This is not an uncommon scenario for software packages.

**Comment by aschempp** [comment]
I disagree, and that's probably the reason we did not find a solution in our discussion. Now you added yours without asking and say it's fixed. Installing the Transifex client on a hosting is very unlikely. As @Toflar said, it even seems to be common for Symfony bundles. Dunno where you have your information from (saying your approach "it's common in a software package").

**Comment by leofeyer** [comment]
It is a very common scenario that language files are not part of the git repo.

You need to distinguish **development** from **distribution**. We are not **developing** the language files, because this is done on Transifex by people who speak the respective languages. Therefore, the language files do not belong into the **development** repo. However, we are **distributing** the language files, therefore the do belong into the **distribution**.

Here is a non-exhaustive list of projects which do it exactly this way:

- Wordpress
- TYPO3
- Joomla
- TinyMCE
- phpMyAdmin
- PrestaShop
- Magento

Even big packages such as OpenOffice or VirtualBox do not clutter their **development** repositories with language files but provide separate packages instead. phpMyAdmin offers a **distribution** with all language files in addition to their **distribution** with only the core language.

And so on …

**Comment by discordier** [comment]
The problem hereby is, that by using composer, the development repo IS the distribution (for most cases).
