### ISSUE TITLE
Broken image links for non-resized images

### ISSUE THREAD

**Issue by Ruudt** [contao/core-bundle#307]
Using a content element Image. When I do not resize an image, the original /files/path is used as URL to that image. But when the folder that contains the image is not set public the image link is broken because the url /files/path looks at /web/files/path. That path will not exist in this case. However, as soon as I resize the same image, inside the same content element, then the /web/assets/image/path will be used and the image displays even though the containing folder is not public.

I should probably not be able to select a non-public file in the image file picker, or the non-resized image version must be displayed from the assets folder (a copy). Perhaps there is another solution?

I recall a similar issue (pre Github) where the second approach was used, though I'm not sure which solution is the best in this case.

**Comment by leofeyer** [comment]
@contao/developers What do you think?

**Comment by aschempp** [comment]
The problem is that we use the same field (`tl_content.singleSRC`) for both images and downloads. For downloads, protected is fine.

I'm not sure if that's a problem we should work around. It's generally a "problem" of the fact that every single folder must be published now. The issue would already be the same in any previous Contao version if the folder was protected.

**Comment by Toflar** [comment]
I don't know if this is a problem. It's just the way it is. I don't think we can solve this. Copying is probably not the right approach as it's a possible security breach (what if you really wanted to protect it?).

**Comment by leofeyer** [comment]
I agree that this probably cannot be fully solved. However, the current behavior is inconsistent, because the resized image will be shown and the not resized image will not. Therefore I tend to adjust the [resizing routine](https://github.com/contao/core-bundle/blob/master/src/Resources/contao/library/Contao/Image.php#L422-L442) to copy the original image if no resizing is required.

**Comment by Toflar** [comment]
Which means if the image is in a protected folder it will be shown anyway because it's copied to a public one? I'm okay with that I just don't know if it's correct.

**Comment by leofeyer** [comment]
If you resize the image, it will be shown anyway. Event in Contao 3.

**Comment by aschempp** [comment]
I don't think that's correct… the image is supposed to be protected. The only allowed solution would be to pipe it and check permission, but thats out of the question to me. Therefore I think we should not display such images at all, but the respective test seems a bit over-engineered to me…

**Comment by leofeyer** [comment]
> I don't think that's correct… the image is supposed to be protected.

The image is only protected unless it is resized. The resized version will be publicly available anyways, even in Contao 3.5. What is the point of protecting the 1024x768px image but to publish the 800x600px version?

**Comment by aschempp** [comment]
That’s what I’m saying. Maybe it shouldn’t be published in either case?

**Comment by leofeyer** [comment]
IMHO, it should be published in both cases. If someone adds an image element, they obviously want the image to be shown.

**Comment by leofeyer** [comment]
As discussed on Mumble on August 13th, the current behavior is correct. Think of a photographer, who wants to show thumbnails of his photos but does not want the original images to be available. He can put the original images into a protected folder and still make thumbnails publicly available.
