### ISSUE TITLE
Correctly use @internal

### ISSUE THREAD

**Issue by leofeyer** [contao/core-bundle#390]
This is a follow-up ticket to #379.

Instead of reading through the same resources over and over again, I have looked at how the `@internal` tag is used in Symfony. Here are some of the comments from the phpDoc blocks:

* They are meant for internal use only and should not be accessed by your own code.
* This method is for internal use only and should never be called directly
* Used by the validator engine. Should not be called by user code.
* This method should not be used or overwritten in userland code.
* This method is public because of PHP 5.3 limitations, do not use it explicitly in your code
* This method is public to be usable as callback. It should not be used in user code.
* This is a purely internal method. If you rely on this method, you are advised to copy/paste the code as this method may change, or be removed without prior notice.

So this means that any `@internal` class must never be instantiated and any `@internal` method must never be called in third-party code. So let's break this down to the core bundle:

Class | Is internal?
----- | ------------
`ConfigAdapter` | Only if we explicitly limit it to be used in service definitions, otherwise no.
Commands | No, because there is no reason why commands should not be extended.
`ContaoDataCollector` | Yes, because nobody is supposed to use this class.
Event listener | Probably no, because why should they not be extended?
`Adapter` | Yes, because it must not be instantiated directly.
`ContaoFramework` | Yes, because it must not be instantiated directly. Always use the service.
`Input::postUnsafeRaw()` | No, because if someone needs the raw value and support for `findPost()`, why should they not use this method?
`Page*::prepare()` | No, because it cannot be called directly anyway and it should be `private` if we do not want child classes to overwrite it.
`ContaoAuthenticator` | ?
`ContaoToken` | No, because there is no reason not to use the class.
`ContaoUserProvider`| ?

So we should think of `@internal` in terms of "do not use it in your code" and not in terms of backwards compatibility at all.

@contao/developers Are you ok with me removing the `@internal` tags according to the table above?

**Comment by ausi** [comment]
IMO `@internal` should not be removed from `ConfigAdapter` because it’s deprecated and should not be used anymore.

**Comment by leofeyer** [comment]
That's why we have added a `@deprecated` tag.

**Comment by Toflar** [comment]
> Yes, because it must not be instantiated directly. Always use the service.

That's a strange reason? If you are using the service you are using the class anyway? :D

**Comment by leofeyer** [comment]
If there are no further comments, I'll be changing the code accordingly.

**Comment by Toflar** [comment]
What about mine?

**Comment by aschempp** [comment]
Sorry but it does not make sense to me at all. Extending the `ContaoDataCollecter` makes as much sense as extending the listeners. If you want to replace a core service for any reason, you might want to extend all of the classes. 

However, we don't want to keep BC for these classes, that's why they should all be internal to me. But you said it's not about BC…

I agree with @Toflar that *using* the class is not limited to creating your own instance. If the adapters are to be used, we can't make the class `@internal` because people rely on their functionality not being changed (= BC).

**Comment by leofeyer** [comment]
Again, `@internal` has only little to do with BC. The `Adapter` class is internal, because people are not supposed to use it. They shall use `$container->get('contao.framework')->getAdapter()` instead.

Our BC promise is based on semantic versioning already. No need for `@api` or `@internal` at all actually.

**Comment by discordier** [comment]
That's the point. Semver covers everything that is not `@internal` and therefore exception to the bc promise. Therefore we should have the tags IMO.

**Comment by aschempp** [comment]
I agree with @discordier 
`@internal` is very much about BC, because it excludes certain classes or methods from BC.

**Comment by leofeyer** [comment]
Ok, so after today's discussion and the [Symfony discussion](https://github.com/symfony/symfony/issues/15977) regarding removal of the `@api` tags, here is an updated version of the table above (changes in bold):

Class | Is internal?
----- | ------------
`ConfigAdapter` | **Yes**
Commands | **Yes**
`ContaoDataCollector` | Yes
Event listener | **Yes**
`Adapter` | Yes
`ContaoFramework` | Yes
`Input::postUnsafeRaw()` | _Still no!_
`Page*::prepare()` | _Still no! The method should be private instead._
`ContaoAuthenticator` | **No**
`ContaoToken` | _Still no!_
`ContaoUserProvider`| **No**

So depending on our new insights, I would now do the following:

* Remove the `@internal` tag from the `Input::postUnsafeRaw()` method.
* Make the `Page*::prepare()` method private.

@aschempp Can you please elaborate why you think that the `ContaoAuthenticator`, `ContaoToken` and `ContaoUserProvider` classes should be internal?

**Comment by aschempp** [comment]
For me, the reason for `ContaoDataCollector`, `ContaoFramework` etc. is `@internal` is because they should be used as services only and not instantiated themselves. That totally applies to the user stuff too, because they are tagged services afair.

Please keep in mind, Symfony is *only* talking about components! In Symfony bundles there is nothing (except console descriptors) marked with `@internal`! It is pretty strange to mark every and all event listener classes as `@internal` just because we use them as a service. It's obvious to me you should not use it. 
In that sense, the only things in our bundle that we should (eventually) mark as internal are exceptions, controllers, `ArrayAttributeBag` and `SymlinkUtil`. These are actual code extension points for developers.
And the `Adapter` should be `final`, but we can't add that because of unit tests…

PS: what do you mean with `Page*::prepare()`?

**Comment by leofeyer** [comment]
Closed in favor of #401.
