### ISSUE TITLE
Deprecated the ClassLoader

### ISSUE THREAD

**Issue by aschempp** [contao/core-bundle#437]
`Contao\ClassLoader` should be deprecated and removed in Contao 5. We should use the Composer class loader, if necessary with a filemap.

Should be an easy-pick.

**Comment by leofeyer** [comment]
+1

**Comment by leofeyer** [comment]
It is not that easy a pick as we thought.

Using a class map implies that the classes are no longer aliased to the global namespace, which will effectively break everything. All content element and module classes extend from `\ContentElement` or `\Module` instead of `Contao\ContentElement` and `Contao\Module`. Many type hints expect a `\Model` instead of a `Contao\Model` and so on.

The class loader should be deprecated to be removed in Contao 5, but I don't think there is an alternative in Contao 4.

**Comment by leofeyer** [comment]
Of course we could add a legacy class loader which automatically adds the global aliases when needed :)

**Comment by aschempp** [comment]
The `ClassLoader` must be deprecated for all extensions. Noone should ever use it. We obviously need to keep it for BC right now.

**Comment by leofeyer** [comment]
I have created a POC in #466.

**Comment by leofeyer** [comment]
The PR #466 has been merged in 42661a616297b030f2e0952e7eaeca77ae8579a4.

**Comment by antoinedavid** [comment]
Hi,
With contao 4.2.4 the composer autoloader dont generate the good path or i miss something.

Here my composer.json :
`{
    "name": "addictic/orphanews-bundle",
    "type": "contao-bundle",
    "description": "Addictic orphanews bundle",
    "license": "LGPL-3.0+",
    "authors": [
        {
            "name": "Addictic",
            "homepage": "https://www.addictic.fr"
        },
        {
            "name": "Antoine DAVID",
            "email": "antdvd@outlook.com"
        }
    ],
    "require": {
        "php": ">=5.5.0",
        "symfony/framework-bundle": "~2.8|~3.0",
        "contao/core-bundle": "^4.2.3"
    },
    "require-dev": {
		"doctrine/data-fixtures": "1.0.*",
		"doctrine/dbal": "~2.3",
		"doctrine/orm": "~2.3",
		"doctrine/doctrine-bundle": "~1.6"
    },
    "conflict": {
        "contao/core": "*"
    },
    "autoload": {
        "psr-4": {
            "Addictic\\OrphanewsBundle\\": "contao/orphanews-bundle/src/"
        },
        "classmap": [
            "src/Resources/contao"
        ],
        "exclude-from-classmap": [
            "src/Resources/contao/config",
            "src/Resources/contao/dca",
            "src/Resources/contao/languages",
            "src/Resources/contao/templates"
        ]
    }
}
`
After a composer update
autoload_static.php generated :
`'Addictic\\OrphanewsBundle\\' => 
        array (
            0 => __DIR__ . '/../..' . '/src',
        ),`
instead of :
`'Addictic\\OrphanewsBundle\\' => 
        array (
            0 => __DIR__ . '/..' . '/addictic/orphanews-bundle/src',
        ),`
autoload_psr4 generated :
`'Addictic\\OrphanewsBundle\\' => array($baseDir . '/src'),`
instead of:
` 'Addictic\\OrphanewsBundle\\' => array($vendorDir . '/addictic/orphanews-bundle/src'),`

**Comment by aschempp** [comment]
This issue is closed, you should open a new one. But it's very likely this is a configuration issue on your system.

**Comment by antoinedavid** [comment]
it's a fresh install
