### ISSUE TITLE
Use Puli for all our resource loading

### ISSUE THREAD

**Issue by Toflar** [contao/core-bundle#439]
Puli solves a lot of issues we have with our resource discovery.
I'd like to illustrate one of the issues and how Puli can help us solve this using an example:

Suppose you want to write a contao bundle that provides additional templates for let's say, a bootstrap integration bundle. So you want to provide a `fe_page_bootstrap` file.

Your bundle structure thus looks like this:

```
src/
    Resources/
        contao/
            templates/
                fe_page_bootstrap.html5
```

Right now, what you are doing is you go ahead and write this into your `autoload.php` file:

``` php
\Contao\TemplateLoader::addFiles([
    'fe_page_bootstrap'    => 'vendor/my-vendor-name/my-bootstrap-bundle-name/src/Resources/contao/templates',
]);
```

Now, there are three main issues here, whereas the last one is the major issue:
- You have to specify the target path the file will be added to, when it's required as dependency in the target application. So it feels sort of strange to add a path to a `TemplateLoader` that does not reflect the real path in your repository. You are using `vendor/my-vendor-name/my-bootstrap-bundle-name/src/Resources/contao/templates` instead of `src/Resources/contao/templates`.
- We have to maintain a `TemplateLoader` component, a language file loading component, a resource discovery for DCA files etc. Everything that's completely redundant because we're talking about how a bundle can tell what kind of files it has and how one can find them.
- The target path is hard coded! In my composer.json I can configure my `vendor` dir to be named `my-custom-vendor-dir` (https://getcomposer.org/doc/06-config.md#vendor-dir) and our templates will not be found. Bummer!

All the issues can be solved using [Puli](http://docs.puli.io/).
### Modifications in the core-bundle:

What we need to do here is obviously change the way we discover the templates from using

``` php
\TemplateLoader::getPath($strTemplate, $strFormat);
```

to something like this:

``` php
$discovery = \Contao\System::getContainer()->get('puli.discovery');
$bindings = $discovery->findByType('contao/templates');

foreach ($bindings as $binding) {
    foreach ($binding->getResources() as $resource) {
        echo $resource->getPath();
    }
}
```
### Usage in the "my-bootstrap-bundle-name" bundle

Instead of 

``` php
\Contao\TemplateLoader::addFiles([
    'fe_page_bootstrap'    => 'vendor/my-vendor-name/my-bootstrap-bundle-name/src/Resources/contao/templates',
]);
```

you'd do something like this:
- Install the Puli CLI
- Execute `php puli.phar bind /src/Resources/contao/templates/* contao/templates`
- This will create a `puli.json` file that contains all the info it needs.
- Done. Templates will be found, issues with path's will be gone and no more resource loading stuff to maintain. Magic!

**Comment by aschempp** [comment]
It would make things configurable. But I hardly believe we need things to be configurable, because as far as I remember Puli was first designed for libraries to share assets across frameworks. That's not the case here. All of your problems could be fixed with template discovery (same as Twig does). And it would even be less work because you don't need to `puli bind`…

**Comment by Toflar** [comment]
"Template discovery" is something we have to write and maintain and we do have to do this for more than only templates. And how is it supposed to find the templates? Is it convention then that you must put them in `src/Resources/contao/templates`? What if I want to have them in `contao-templates`?

> And it would even be less work because you don't need to puli bind…

This is one very simple command. Not really what I call "work".

Also, I very much believe in the idea behind Puli and I think that many projects will make use of it in the future so it will sort of become "normal" to use it. Developers will go like "oh, discovered by Puli and the binding name is 'contao/templates', alright, I know what to do". Whereas otherwise they have to know about our very project specific conventions about how resources are discovered.

**Comment by aschempp** [comment]
>  Is it convention then that you must put them in src/Resources/contao/templates? What if I want to have them in contao-templates?

Yes it is. It's legacy stuff, we agreed it's a convention. It will be dropped eventually and probably replaced by Twig, so adding new features is kind of a bad idea.

I do agree about Puli, but I haven't come across a real use case for me personally. Though I only created like [one real library](https://github.com/terminal42/webling-api), which has no assets…

**Comment by webmozart** [comment]
This is very much a use case for Puli :) However, I wouldn't use Discovery, but the Repository. Resource directories are mapped to "Puli paths". Then you can use those Puli paths to load your resources.

In a bundle named "my/bundle":

~~~
$ php puli.phar map /my/bundle src/Resources
~~~

Loading a template through Contao's loader (pseudo code):

~~~php
$loader->loadTemplate('/my/bundle/contao/templates/index.html5')
~~~

All that's needed is to pass Puli's `Repository` to the template loader, which basically just does this internally:

~~~php
// $path = /my/bundle/contao/templates/index.html5 in the above example
return $repo->load($path)->getBody();
~~~

The benefit is that your loader is now independent of any particular directory convention. The same loader can be used to load any other template from the Puli repository and can be made to work with relative paths (`layout.html5`, `../sidebar.html5`). You can use Puli paths to refer to assets in HTML files (e.g. `../public/css/style.css`), independent of where those assets are installed on the web server. In the future, IDEs like PhpStorm will hopefully even provide auto-completion for Puli paths.

Look at [Puli's Twig Extension](https://github.com/puli/twig-extension) for how this could be implemented.

**Comment by DanielSchwiperich** [comment]
Viewpoint from an outside Contao developer / agency:
One reason my agency decided years ago to use contao instead of drupal, typo3, etc was it's approach: Convention over configuration. Easy to learn, steady experience. For users and developers. 

Right now that's not always the case anymore. Staying with @Toflar's example: 
Right now I could put my templates anywhere I want and configure the template loader accordingly in the autoload.php.
With Puli I could do the same in a (to me) much nicer way. It also offers me abilities to build a bundle not only for contao, maybe also for drupal. (if understood the capabilities correctly)

I think Contao should integrate Puli somehow. Especially to attract *foreign* developers. Puli maybe has the chance to be the next composer thing. I don't know.  And if not, it still would add easier integration workflows. 

But I also think Contao needs some "Convention over configuration" again. In this Case: *Autodiscovery*.
Why cannot I just mark my contao module/bundle as `contao-bundle` in the composer.json and the core-bundle templateloader builds a cached registry by itself going through all registered contao-bundles checking the `vendor/my/bundle/src/Resources/contao/templates` Dirs. 
Couldn't we even use Puli for the Autodiscovery? Check for all `contao-bundle`s and set the default resource mappings? 

Sorry if I got something wrong. Have been to many hours today.

**Comment by leofeyer** [comment]
As discussed in Haag, we want to see if Puli will be integrated in Symfony. Once we know, we can discuss if and how to use it for Contao.

**Comment by leofeyer** [comment]
As discussed in Mumble on November 30th, 2017, we will close the ticket as Puli has not been integrated in Symfony (and it does not seem like it will any time soon).
