### ISSUE TITLE
PHP Session Security Hardening

### ISSUE THREAD

**Issue by xchs** [contao/core-bundle#443]
If Contao runs over an encrypted connection, we could enable some session cookie hardening attributes. The **“Secure” cookie attribute** instructs web browsers to only send the cookie through an encrypted HTTPS (SSL/TLS) connection (see e.g. [OWASP Session Management Cheat Sheet](https://www.owasp.org/index.php/Session_Management_Cheat_Sheet#Secure_Attribute)).

``` yml
# app/config/config.yml

# Framework configuration
framework:
    session:
        …
        cookie_secure: %cookie_secure%
        cookie_httponly: true
        …
```

(see [Symfony FrameworkBundle Configuration](http://symfony.com/doc/current/reference/configuration/framework.html#cookie-secure))

**Comment by Toflar** [comment]
We did have that in Contao 3 already, +1.

**Comment by aschempp** [comment]
I wonder why this is not part of the Symfony standard edition?

**Comment by discordier** [comment]
Because the standard edition supports websites not being soly provided via https.
Be aware that when setting this, the cookies will not be sent to plain sites and as this is configurable only system wide, you will not be able to serve one page root via HTTP and another one HTTPS.
Therefore I doubt this will be practical to implement and I strongly discourage to enable this by default.

**Comment by Toflar** [comment]
I was mainly talking about `cookie_httponly`. `cookie_secure` obviously has to be disabled by default.

**Comment by discordier** [comment]
Ah, ok. I thought you were talking about both.

**Comment by leofeyer** [comment]
So actually, we do not have to change anything, right? `cookie_secure` is false by default and `cookie_httponly` is true by default – exactly as we want it.

**Comment by Toflar** [comment]
Contao should probably have a response listener for the 'frontend' route attribute and dynamically set the config for cookies depending on the root https settings? I might well want to secure only 1 domain out of 5.

**Comment by aschempp** [comment]
That would not work with the container setting of Symfony, right?

**Comment by aschempp** [comment]
Also we don't know if the same domain can be accessed with and without TLS.

**Comment by leofeyer** [comment]
I also think that there should be no configuration magic.

**Comment by Toflar** [comment]
Imho that issue is not related to "configuration magic" at all. Setting it in the configuration file will store the parameter in the container, yes. But all it does is passing it as an options array to the `NativeSessionStorage` which itself calls `setOptions()` where the parameter eventually gets set as an ini parameter using `ini_set('session. cookie_secure', $value);`. So imho, we could easily set this in an event listener at runtime.

The problem is, Symfony does not consider serving multiple domains with different settings out of the box. Contao, however, does. If we don't do anything, 99.9% will never set `cookie_secure = true` and even if somebody thought of doing so, they won't be able to set it for one domain only which means, all domains have to be served through https. It would be a great security feature if we supported it out of the box.

In my opinion, the `Use https for sitemaps` setting in the root page settings should be renamed to `Serve this page via https` which should automatically do a few things:

- Redirect all `http://` requests to `https://`
- Prefix all URL's of that domain with `https://` when generating absolute ones.
- Setting `cookie_secure` on all the pages of that domain.

**Comment by aschempp** [comment]
> … should automatically do a few things …

I like that idea. Though I'm always redirecting to *https* in my `.htaccess`, it would make it a lot easier for most users to set that in Contao. As discussed before, there is no reason to serve a page from *http* if it can be accessed from *https*.

**Comment by Toflar** [comment]
Nobody will stop you from manually redirecting to `https` before the PHP process even gets fired up :-) But yes, most users just want to have that nice checkbox and it works and cookies are automatically secured. This is what we need to do, in my opinion.

**Comment by leofeyer** [comment]
> - Redirect all `http://` requests to `https://`
> - Prefix all URL's of that domain with `https://` when generating absolute ones.
> - Setting `cookie_secure` on all the pages of that domain.

I agree with everything but the last one. As you have explained yourself, we must only set `cookie_secure` to `true` if **all** URLs of the website are available via HTTPS. If one domain has an SSL cert and the other one does not, we must not. Am I right?

**Comment by Toflar** [comment]
That's why I want it to be an event listener. It's a setting per Contao root page. So if root page A for domain domain.tld is set to use https, all cookies of that root page's sub pages shall use secure cookies :)

**Comment by leofeyer** [comment]
As discussed in Mumble on April 21st, @Toflar is going to check if and how the cookie_secure option can be set at runtime in an event listener. @leofeyer will take care of the rest.

**Comment by Toflar** [comment]
Fasten your seatbelts, novel following 😄  I checked this and I think it's very well possible to change the `session.cookie_secure` value at runtime, although not in an event listener but in our own `Contao\CoreBundle\Session\HttpsAwareNativeSessionStorage` class.

So, in Symfony all the session stuff has been properly abstracted so you can mock session stuff in unit tests. That being said, the `session` service basically consists of a "session storage". The session storage implements the `SessionStorageInterface` and thus handles the way sessions are started, regenerated, saved etc. Basically, we have three important storage classes here:

* `NativeSessionStorage` provides a storage using the built in php `session_*()` functions.
* `PhpBridgeSessionStorage` provides a bridge for legacy applications that start the sessions themselves using `session_start()`.
* `MockArraySessionStorage` is just a simple storage that keeps everything in an array (basically for tests).

There is at least one more but they are not important for now.

Now, a session storage **MAY** accept an additional "handler". The `MockArraySessionStorage` does not have one but `NativeSessionStorage` e.g. accepts one so you can define where the sessions are stored. There are again multiple implementations, obviously the `NativeFileSessionHandler` which uses the default PHP session files (php.ini value of `session.save_path`) but also you can store the session in a DB using the `PdoSessionHandler`, or Mongo DB, Memcached etc.

Both, the "storage" as well as the "handler" can be configured thanks to the framework bundle, like this:

```yaml
framework:
    session:
        storage_id: ~  # Default: session.storage.native
        handler_id: ~ # Default: session.handler.native_file
```

To sum up: By default, Symfony uses the native php storage and the native php file handler.

For us, the `handler_id` is fine, anybody that wants to change where the session stuff is stored, can change it themselves. We want to have a closer look at the `storage_id` and thus `session.storage.native`.

Here's the service definition:

```xml
<service id="session.storage.native" class="Symfony\Component\HttpFoundation\Session\Storage\NativeSessionStorage">
    <argument>%session.storage.options%</argument>
    <argument type="service" id="session.handler" />
     <argument type="service" id="session.storage.metadata_bag" />
</service>
```

As you can see, the first argument is the `session.storage.options` parameters from your configuration. Basically that's where the `cookie_secure` comes from. When we have a look at the `__construct()` of `NativeSessionStorage`, we can see that it calls `NativeSessionStorage::setOptions()` where it eventually sets the options: `ini_set('session.'.$key, $value);`.

We sum up again: We were looking for the place where `ini_set('session.cookie_secure', $value);` is being set. Voilà: It happens based on your configuration while constructing the object of `NativeSessionStorage`.

We cannot change this option later on using an event listener, because the `session` service does not really know about its storage. You cannot call `getStorage()` and apply changes at runtime, we have to do it **before the session is started**.

Conclusion: What we need to do is changing the `session.storage.native` to our own `contao.session.https_aware_storage_native` in a compiler pass. Our servivce should look something like this:

```yaml
contao.session.https_aware_storage_native:
    class: Contao\CoreBundle\Session\HttpsAwareNativeSessionStorage
    arguments:
        - "%session.storage.options%"
        - "@session.handler"
        - "@session.storage.metadata_bag"
        - "@contao.framework"
        - "@request_stack"
```

And the class basically like this:

```php
<?php

namespace Contao\CoreBundle\Session;

use Contao\CoreBundle\ContaoCoreBundle;
use Contao\CoreBundle\Framework\ContaoFrameworkInterface;
use Symfony\Component\HttpFoundation\RequestStack;
use Symfony\Component\HttpFoundation\Session\Storage\Handler\NativeSessionHandler;
use Symfony\Component\HttpFoundation\Session\Storage\MetadataBag;
use Symfony\Component\HttpFoundation\Session\Storage\NativeSessionStorage;
use Symfony\Component\HttpFoundation\Session\Storage\Proxy\AbstractProxy;

class HttpsAwareNativeSessionStorage extends NativeSessionStorage
{
    /**
     * @var ContaoFrameworkInterface
     */
    private $framework;

    /**
     * @var RequestStack
     */
    private $requestStack;

    /**
     * HttpsAwareNativeSessionStorage constructor.
     *
     * @param array                                                            $options
     * @param AbstractProxy|NativeSessionHandler|\SessionHandlerInterface|null $handler
     * @param MetadataBag                                                      $metaBag
     * @param ContaoFrameworkInterface                                         $framework
     * @param RequestStack                                                     $requestStack
     */
    public function __construct(
        array $options,
        $handler,
        MetadataBag $metaBag,
        ContaoFrameworkInterface $framework,
        RequestStack $requestStack
    ) {
        parent::__construct($options, $handler, $metaBag);

        $this->framework = $framework;
        $this->requestStack = $requestStack;
    }

    /**
     * Override start method to set the cookie.secure setting depending on the
     * root page settings.
     *
     * @return bool
     */
    public function start()
    {
        if ($this->started) {
            return true;
        }

        // Make sure the framework is initialized
        $this->framework->initialize();

        $request = $this->requestStack->getCurrentRequest();

        global $objPage;

        if (ContaoCoreBundle::SCOPE_FRONTEND === $request->get('_scope')
            && null !== $objPage
            && $objPage->rootUseSSL
        ) {
            parent::setOptions(['cookie_secure' => true]);
        }

        return parent::start();
    }
}
```

That should do it.
Hope you liked this little insight on how Symfony sessions work 😄 

Remarks:
* Completely untested!
* That `global $objPage` call there prevents from proper unit testing. We should find a way to mock the current page object, I think.

**Comment by aschempp** [comment]
As far as I know we're using `PhpBridgeSessionStorage`, isn't that a problem?

**Comment by Toflar** [comment]
It would be one, yes. But no, we don't :)

**Comment by discordier** [comment]
If I understood correctly, this would mean the application must not use an alternative session storage aside from ours or otherwise Contao will completely break.
Putting such restrictions in place and changing how Symfony core components are working feels completely wrong to me.

Am I the only one who thinks it is completely wrong to change the configured service of the application into our own which behaves unpredictable from the view of other Symfony bundles.
I mean, Contao 4 was meant to be a drop in bundle which should work in any existing Symfony application.

**Comment by Toflar** [comment]
> If I understood correctly, this would mean the application must not use an alternative session storage aside from ours or otherwise Contao will completely break.

You did not understood correctly, no. Nothing breaks at all. If you use your own session storage (for which I have absolutely no use case. Please do not mix storage and storage handlers!) then you are also responsible for setting `cookie.secure`. Simple as that.

**Comment by discordier** [comment]
That's what I said above, my other handler is then responsible of setting it like Contao expects it to be, otherwise Contao will stop working (as it will not have any Cookie anymore).
And for the usecase argument, if WE have a usecase here by relying on a own implementation to implement this feature, why shouldn't other people have one too in order to provide another, unrelated, feature?

The problem I see here is, that the used implementation is mutually exclusive, it is either theirs or ours.
By relying on the fact to use ours, we are going to isolate ourselves against usage in some other applications which I would rather not do.

**Comment by leofeyer** [comment]
> Contao will stop working (as it will not have any Cookie anymore)

Of course it will still have a cookie. Only the `cookie_secure` option will not be set (unless explicitly configured).

**Comment by Toflar** [comment]
> Of course it will still have a cookie. Only the cookie_secure option will not be set (unless explicitly configured).

Correct.

**Comment by discordier** [comment]
It still feels wrong to me, but you might be right.

Second aspect which feels as bad habit to me is, we will always boot the legacy framework, even for non Contao requests, am I right?

**Comment by Toflar** [comment]
> Second aspect which feels as bad habit to me is, we will always boot the legacy framework, even for non Contao requests, am I right?

Implementation detail. Of course you can check `_scope` on the request attributes first and only initialize the framework if it's a Contao front end request.

**Comment by leofeyer** [comment]
@Toflar There is a problem:

```
The service "contao.session.https_aware_storage_native" has a dependency on a non-existent service "session.handler".
```

**Comment by leofeyer** [comment]
As discussed in Mumble on May 12th, we would need the HTTPS information before the session is started, which however is before the global page object is available. This could be solved with the Symfony CMF router.

**Comment by leofeyer** [comment]
The current CMF router implementation attempt is here: https://github.com/contao/core-bundle/pull/1653

**Comment by leofeyer** [comment]
Since cookies are meanwhile [secure by default](https://symfony.com/blog/new-in-symfony-4-2-auto-secure-cookies) in Symfony, we can close this issue.
