### ISSUE TITLE
[4.2.beta1] Theme issues

### ISSUE THREAD

**Issue by Toflar** [contao/core-bundle#477]
When you resize the browser manually the burger appears, but you cannot click on it. You have to reload the page so you can open it.
Also, there seems to be something wrong with the menu itself:
![bildschirmfoto 2016-04-29 um 11 24 28](https://cloud.githubusercontent.com/assets/481937/14912535/3d35ff04-0dfd-11e6-9f9e-139531641253.png)

**Comment by leofeyer** [comment]
> When you resize the browser manually the burger appears, but you cannot click on it. You have to reload the page so you can open it.

Yes, that's true, because the markup needs to be adjusted on smaller screens and this does not take place if you just resize the window.

> Also, there seems to be something wrong with the menu itself:

It is not wrong, it is just missing the icons (as you know). It is not supposed to say "Benutzer yanick.witschi", "Frontend-Vorschau" and "Abmelden" – there should be three nice icons.

**Comment by fritzmg** [comment]
Also, just a personal preference, the `#left` would look and feel a little more clear with such styling:

![c42left](https://cloud.githubusercontent.com/assets/4970961/14938161/92ce8b88-0f1b-11e6-8db8-3bc319960706.png)

(similar to the old one)

**Comment by leofeyer** [comment]
Since we are all not happy with the current solution, I have mocked up some more navigation variants.

### 1. Boxes

This is pretty much @fritzmg's suggestion with some spacing in between the boxes and a litte more padding.

![boxed](https://cloud.githubusercontent.com/assets/1192057/15039090/15101490-12aa-11e6-8c47-0ee8d387fdea.png)

### 2. Accordion

This is very similar to the first one but the navigation is an accordion with only one open pane at a time.

![accordion](https://cloud.githubusercontent.com/assets/1192057/15039102/44a07682-12aa-11e6-8332-b6d0edee2962.png)

### 3. Group icons only

This one does not have icons for every menu item but only for the groups. This would drastically decrease the number of icons required for third-party extensions.

![group-icons](https://cloud.githubusercontent.com/assets/1192057/15039131/89ac666e-12aa-11e6-9cb1-236c637c9b3c.png)

### 4. No icons

This one does not have any navigation icons at all. Definitely one of my favorites ;)

![no-icons](https://cloud.githubusercontent.com/assets/1192057/15039141/9eb7b9e6-12aa-11e6-9788-5e79fe71c5d3.png)

@contao/developers @frontendschlampe @MacKP @denniserdmann What do you think?

**Comment by aschempp** [comment]
I think the accordion is a bad idea because it will require more clicks for the same action. I can imagine this being a user profile preference though, some people might like it (I probably would, but I know my clients would not).

My personal favorite is v3, assuming it would also get the arrows for open/collapsing the headers? I prefer no margin between the sections, they're already separated enough by color and headline.

**Comment by fritzmg** [comment]
Hm, can't pick a favorite, I kind of like aspects in all of the proposed mock-ups :grin: 

I like the additional spacing and padding in __1__. I also the accordion idea in __2__, though I share the same concerns as @aschempp. I also like __3__ because it's more simplistic and still clear. And __4__ is an improvement to the current state and just feels better while being very simplistic.

**Comment by fiedsch** [comment]
I like the "No Icons" version best. I would additionally use the highlighting of the level one headings as in "Group icons only" and use indentation (together with smaller font size) to show the hierarchical structure.

My _personal_ argumentation against icons in the menu: there are so many icons I can not memorize their meaning. So they are useless _for me_.

**Comment by DanielSchwiperich** [comment]
V1 and V3 look best to me. From an UI standpoint I think having icons is important to give the user visual anchors. They can more easily identify the section they want to go next through memorizing / learning. 

But as @fiedsch said to many icon destroy the effect. Having a normal contao installation without 50+ modules and where you can collapse not often needed sections V1 would work best I think. 
V3 looks cleanest though to me. Like it too. 

Don't like V4, to hard to navigate since all looks the same and even the hierarchy is not really goog noticable. 

V2 same concerns like @aschempp

**Comment by OMOSde** [comment]
Mir persönlich gefällt Variante #Boxes (v1) am besten. Der Abstand macht die Boxen besser erfassbar und bzgl. der Icons schließe ich mich Daniel an. 

#Accordion heißt für mich 'immer nur eins offen', damit fällt es für mich bzgl. Usability leider durch.

**Comment by scuben** [comment]
V3 ist meiner Meinung nach die beste Variante. V2 fällt wegen des zusätzlichen Klicks weg. V4 wirkt verloren ohne eigenen Background. V1 hat unnötigen Space der nur störend Wirkt und die Harmonie des Gesamtbild beeinträchtigt.

**Comment by lionel-m** [comment]
I like the V4 but with the white background and a header for each menu group as in V1 to keep a good contrast.

**Comment by MacKP** [comment]
Nice work!
My thoughts:
V1, V2, V3 looks so boxed ;-) I think it's not necessary. Less Icons are not bad I think. But can be a two sided thing. They can help to find a Navigation Point. But there can be to much. Would be nice, when you can toggle then on and off ^^

V2: shouldn't be make it.. it's realy against working with it like an admin. I am klicking everywhere when I develop a new Porjekt. Not only in one group.

I really like V4. But there are some important things missing ;-) :

- Contrast for the active Item isn't enough (but maybe i haven't the right color there) -> https://leaverou.github.io/contrast-ratio/#%237AB249-on-%23EAEAEA
-  The active Item should marked with more than an color change. Maybe bold / underline ore putting it to the right side? Only the color isn't enough...
- The submenu Items could be a little bit moved to the right side ore have an dot (then you can see it better).
- And maybe to clear things up an line `<hr>` between the Groups?

regards

BTW: I realy like the new Icons! The contrast is so great and clear :)

**Comment by eBlick** [comment]
I'd prefer no icons but nevertheless boxed (V 1 without icons).
Icons might be useful when self-explaning and not text available (due to missing space).
In this case there is plenty of room for text and this is absolutely sufficient. No one looks at the icons when having navigation text.

**Comment by netzarbeiter** [comment]
First of all, a big thank you to the people involved.

I really like the new icon set and I’m looking forward to see it in action.

I prefer version 1 (Boxes) and I’ll hope the new backend theme goes with the icons and without accordion.

**Comment by Sascha-Brandhoff** [comment]
Definitiv Boxes

**Comment by mlaubacher** [comment]
I like the following:
- boxes with spacing as in #1
- no icons as in #4

reasons:
boxes with spacing:
groups are visually emphasised and therefore better recognised

no icons:
not needed in this context, to small and not distinguished enough to be of help for the navigation. Also Important: Icons are used for "actions" in the contao backend widely and if there are as little as possible similar icons elsewhere, it is much clearer that an icon means an "action".

**Comment by marcuslelle** [comment]
I also like #4 the best but having issues with green on grey for the current item.
#3 would be a compromise, close enough to #4 but more "familiar". I guess that would help "no changes please"-people adjust to it.

Anyway: Each version is an improvement to the current state. Great work!

**Comment by somasundaram** [comment]
I like the third version. It's clearly arranged. 
And the developers are cheering. They do not have to search a new icon for each extension.

**Comment by Loilo** [comment]
I like version 3 and 4 best. Looks nicely clean.
Can't say how much I use the existing icons for orientation so I might miss them when I actually use the new design. We'll see.

**Comment by leofeyer** [comment]
Ok, here is a quick interim result:

| Variant | Votes |
| ------- |-------|
| 1. Boxes | 5 |
| 2. Accordion | 0 |
| 3. Group icons only | 5 |
| 4. No icons | 6 |
| 5. No icons boxed | 3 |

The last one (5. No icons boxed) was not a mocked up variant but requested several times, therefore I have added it.

**Comment by denniserdmann** [comment]
+1 for Version 3 - Group icons only

**Comment by bytehead** [comment]
+1 for v3

**Comment by Toflar** [comment]
I'm with v3 or v5 as well.

**Comment by alnv** [comment]
+1 for 3 Group icons only

**Comment by christianromeni** [comment]
+1 V1
Icons are important for most Users... Not for devs.. But users love them...

**Comment by fritzmg** [comment]
Nevertheless I vote for V__1__ as well.

**Comment by NicolasGoerlach** [comment]
+1 for Version 3

**Comment by zonky2** [comment]
+1 V1
at small devices may be without text/label - (only icons)

**Comment by kikmedia** [comment]
Well, from a usability point of view, you need both - text and icons, because you need a representation which gives a semantic meaning for everyone.

While I personally prefer a text-only version like in (4) or (5) (which will be fine in screen readers) there will be cases when there are people not being able to read at all, so you have to provide some kind of graphic representation.

Version (5) will give a more structured view than (4).

So, my vote clearly goes to (5) with a _configurable option_ for showing icons for _every_ item (not only sections).

Anyway, icons should be meaningful if activated. In all those years with Contao I experienced that most of the icons are not, and furthermore most of the icons habe a lack of proper contrasts, proper colours for the colour blind and so on. So you will have to add support for creating an individual set of icons too.

**Comment by leofeyer** [comment]
I have adjusted the theme according to the results of the voting in 271c61212c94e4ca9bdf2b5617ea7e0b61f9e2bf. Thank you everyone for your feedback.
