### ISSUE TITLE
[4.2.0] Installer Problems

### ISSUE THREAD

**Issue by christianromeni** [contao/core-bundle#522]
I got some strange errors after updating from 4.1 to 4.2.
I wanted to enter http://domain.de/install.php (/web/install.php) to update the database.
But I'm getting this error:

```
Fatal error: Call to undefined method Contao\InstallationBundle\Controller\InstallationController::indexAction() in /home/php-deploy/sites/dev/domain.de/web/install.php on line 26
```
After checking the latest installer-bundle I noticed the change here:
$response = $controller->indexAction(); became $response = $controller->installAction();

So I tried what would happen if I just changed that call. Did it, and got the next error:

```
Fatal error: Uncaught exception 'Twig_Error_Syntax' with message 'Unknown "path" function in "@ContaoInstallation/main.html.twig" at line 135.' in /home/php-deploy/sites/dev/domain.de/vendor/twig/twig/lib/Twig/ExpressionParser.php:574 Stack trace:
#0 /home/php-deploy/sites/dev/domain.de/vendor/twig/twig/lib/Twig/ExpressionParser.php(351): Twig_ExpressionParser->getFunctionNodeClass('path', 135)
#1 /home/php-deploy/sites/dev/domain.de/vendor/twig/twig/lib/Twig/ExpressionParser.php(144): Twig_ExpressionParser->getFunctionNode('path', 135)
#2 /home/php-deploy/sites/dev/domain.de/vendor/twig/twig/lib/Twig/ExpressionParser.php(84): Twig_ExpressionParser->parsePrimaryExpression()
#3 /home/php-deploy/sites/dev/domain.de/vendor/twig/twig/lib/Twig/ExpressionParser.php(41): Twig_ExpressionParser->getPrimary()
#4 /home/php-deploy/sites/dev/domain.de/vendor/twig/twig/lib/Twig/Parser.php(144): Twig_ExpressionParser->parseExpression()
#5 /home/php-deplo in /home/php-deploy/sites/dev/domain.de/vendor/twig/twig/lib/Twig/ExpressionParser.php on line 574
```

Can this be reproduced by someone else?

**Comment by bytehead** [comment]
Did you update your `install.php` file according to the one from the [standard-edition](https://github.com/contao/standard-edition/blob/master/web/install.php)?

**Comment by bytehead** [comment]
And don't forget [this lines][https://github.com/contao/standard-edition/blob/master/composer.json#L24-L29] in your `composer.json`.

**Comment by fritzmg** [comment]
> Did you update your install.php file according to the one from the standard-edition?

Is it not automatically updated when doing a `composer update`?

**Comment by christianromeni** [comment]
Ok.... So all the changes in the standard edition have to be transferred to the local installation manually??
That is realy strange.....

**Comment by bytehead** [comment]
I only use the `contao/core-bundle`  (instead of the whole `contao/standard-edition`), so I had to update this ones by myself.

**Comment by micha-nerdlichter** [comment]
I still have some issues with the new installer, even with a clear install from ```contao/standard-edition``` (4.2.1).

I download the repo and do the composer install. Everything works fine. I start the ```install.php``` and accept the license. Then I get redirected to the Backend login and it fails with a TableNotFound Exception. This seems normal, as my database is blank and the Install script is supposed to create that. But at this state I can't call the ```install.php``` anymore without being redirected to a (broken) Backend login.

By looking at [InstallationKernel.php](https://github.com/contao/installation-bundle/blob/bc72b41e2274e6db75542acd3cdd78a063b30e18/src/HttpKernel/InstallationKernel.php#L73-L74) this seems pretty clear. The function [```canBootRealSystem()```](https://github.com/contao/installation-bundle/blob/bc72b41e2274e6db75542acd3cdd78a063b30e18/src/HttpKernel/InstallationKernel.php#L61-L66) checks for ```parameters.yml``` (which was created by composer) and ```localconfig.php``` (which was created by the Installer when I accepted the license). But the system isn't ready to boot as there are no tables in the db. And I can't run the Installer to create the tables, because I get redirected.

@leofeyer what are the intensions for this redirect? By commenting it out I forced the installer to load and got finally the form to set the install password. As soon as I do that it fails again with the ```'Unknown "path" function in "@ContaoInstallation/main.html.twig" at line 135``` Error that @christianromeni reported.

And yes, I used the original ````install.php````, ```composer.json``` and ```composer.lock``` so [the autoload section] (https://github.com/contao/standard-edition/blob/2aabeae1aa37f160515d53d2da3b64ccb5f5512f/composer.json#L24-L29) is included.

**Comment by aschempp** [comment]
You should be redirected to `contao/install` (away from `install.php`), but not to the backend.

@contao/developers maybe the login screen appears because `contao/install` is protected by the backend firewall? I never had that issue though.

**Comment by fritzmg** [comment]
See  https://github.com/contao/installation-bundle/commit/4199b542cde4c22aa51f058924a934c52dbd6439 and https://github.com/contao/core-bundle/issues/541#issuecomment-233172927

**Comment by fritzmg** [comment]
@aschempp no, the redirect is still wrong. It is fixed in the hotfix/1.1.2 branch.

**Comment by micha-nerdlichter** [comment]
Thanks, this really helped. Why isn't the hotfix merged to master so that composer installs the correct ``` InstallationKernel.php```?

**Comment by fritzmg** [comment]
composer will not install it automatically, when it is merged into the master branch - unless you specifically required the master branch. You can however require the hotfix/1.1.2 branch (`dev-hotfix/1.1.2`) if you want to install it, before the official release of `1.1.2`.

**Comment by micha-nerdlichter** [comment]
You're right, I had to add ```"contao/installation-bundle": "dev-hotfix/1.1.2 as 1.1.2"``` to the ```composer.json```
