### ISSUE TITLE
Drop the contao:version command

### ISSUE THREAD

**Issue by leofeyer** [contao/core-bundle#665]
As we keep telling people, Contao does not really have one version number anymore but each component has its own. Therefore it seems misleading to have a `contao:version` command, which outputs the version number of the core bundle, so I think we should drop it.

@contao/developers What do you think?

**Comment by ausi** [comment]
+1

`composer show contao/*` can be used as an alternative.

**Comment by DanielSchwiperich** [comment]
Wouldn't this be a BC breaking change?

**Comment by Toflar** [comment]
Well to get only the version it needs a bit more command line knowledge.
An example for the record: `composer show contao/core-bundle | grep versions | awk '{ print $4 }'`.

> Wouldn't this be a BC breaking change?

It would and imho there's no reason to remove it because the data it returns is correct. We could adjust the description from `Outputs the Contao version.` which is not true to `Outputs the contao/core-bundle version.`.

Or we could get more verbose and go for `Outputs the contao/core-bundle version. Note that this command is deprecated and will be removed. You can get the same information from Composer directly by e.g. "composer show contao/core-bundle | grep versions | awk '{ print $4 }'"`.

That way people using the core-bundle version for e.g. cron jobs at least have an alternative.

**Comment by discordier** [comment]
I agree with @Toflar, there is no reason to remove it (aside from it being mostly useless nowadays).
I also favor causing it to output a more verbose message of being deprecated and hinting to use the proper tool (composer) for hunting down the information.

**Comment by leofeyer** [comment]
I have created a PR: #668
