### ISSUE TITLE
Raise minimum PHP version to PHP 7

### ISSUE THREAD

**Issue by Toflar** [contao/core-bundle#701]
I think we should raise the minimum version for the upcoming contao 4.4 to PHP7.
PHP 5.6's active support was dropped by the end of 2016 and it's in security fixes only mode now.
See http://php.net/supported-versions.php.

Given the fact that Contao 4.4 will be our first LTS version and we'll have to support it until 2020 (!), I think we **must** drop support for PHP 5.*.

**Comment by leofeyer** [comment]
I'd love to, but I don't think we can. You know how web hosting companies are …

**Comment by asaage** [comment]
Web hosting companies are like "composer??? shell???" 😄

**Comment by Toflar** [comment]
Really, we should stop thinking like that. I don't care about these kind of hosters. Nobody should.
Let's just make a poll on "does your hoster support PHP 7" and see what the results are. I'm sure most of them do because they would be extremely stupid if not. I mean you can save so many resources...

**Comment by DanielSchwiperich** [comment]
if so, then please php 7.1 because of nullable parameter and return types. 
But debian does not support this yet sadly

Even companies like strato and 1und1 support php7

But raising makes only sense if we make use of the new features. I wonder if using scalar type declarations for parameters and return types would be BC breaking? Most likely depending on contaos definition if phpdoc counts towards public api?

**Comment by aschempp** [comment]
I agree with @DanielSchwiperich, it only makes sense to raise minimum dependencies if we use such features. Same discussion as with Symfony 3.2…

**Comment by Toflar** [comment]
I disagree. It's absolutely not the same discussion as with Symfony 3.2.
This discussion is not about whether we need the features or not. You can always ignore technological advance and just stick to the old platform. We could still build for PHP 4 and say "we don't need the new features". But I repeat myself: if we do this, we'll have to stick with an outdated platform, containing security vulnerabilities until 2020.
This means we'll be maintaining a piece of software, providing bugfixes and security related fixes that run on a platform that itself is not maintained anymore? Why should this make sense?

I agree we don't need to. Everybody is responsible for updating the platform themselves. But I think we should set an example and force people to update. E.g. PhpUnit 6 is now PHP7 only. We can never use it as long as we stick with 5.6. So what if 2019 we run into bugs in PhpUnit itself and no more updates on old PhpUnit versions are provided? Do you want to raise the minimum version of PHP in Contao version 4.4.22?

**Comment by agoat** [comment]
I agree with @Toflar. Almost all major providers already have PHP7 (which is already available for a year btw.). And all the others will surely follow by the end of the year. Contao 4.4 is scheduled to be released in mid-2017. So I see no problem to take PHP7 as a minimum requirement.

**Comment by leofeyer** [comment]
How many Unix LTS distributions are still shipping PHP 5?

**Comment by aschempp** [comment]
I'm actually proposing another option: Keep 5.x for Contao 4.4, and raise the minimum version to 7 for the next version. That would mean an LTS of Contao 4 is guaranteed to run on your existing server for whatever reason you need to.

**Comment by discordier** [comment]
Next version being what? Next minor? Next patch level? Next LTS?

I totally agree with @Toflar and am more than willing to bury PHP 5 as deep as we can.

It is simply totally out of question to support PHP5 up until 2020 where it is only of academic relevance (if any).
We would also prevent ourselves from using ANY of the new features PHP 7 brings us until the next LTS in 2020.

For me it is not only a matter of stating an example (along with PHPUnit and others) to force up to date software, moreover it is a matter of NOT stating an example that it is ok (and maybe even encouraged) to use PHP 5.X in 2020.

Therefore let's get rid of PHP 7 and do it fast!

**Comment by aschempp** [comment]
Obviously the next minor version (4.5), which means we can start using PHP 7 features in November (or actually when we start development of 4.5). Be aware that we are supporting Contao 3.5 until 2019 as well with support of PHP 5.3, which is outdated already. I don't really see an issue with this, as we are forward-compatible.

**Comment by agoat** [comment]
So we have Contao 3.5 supporting PHP 5. Why should we delay the use of new techniques in contao 4, just to rely on no longer maintained products?

It's a huge step from Contao 3.5 to 4, so everybody can then also make the step from PHP 5 to 7.
As already said, the Contao 3.5 LTS is supported until 2019.  IMO that's enough legacy support.

Contao 4 is the future - Contao 3.5 is legacy with LTS.

**Comment by discordier** [comment]
The issue is, that we HAVE TO be backwards compatible to a version that is de facto EOL already up until 2020.
Contao 3.5 is not of an issue here, as it is feature complete and frozen.

By keeping support for 5.X we have

On the benefit side:
- compatibility with crap hosters too lazy to upgrade to PHP 7.

On the downside:
- We MUST NOT use PHP 7 features in Contao 4 LTS.
- We will likely have to alter most bugfixes before backporting them to Contao 4.4 from Contao 4.4+ (4.5 up to 4.9) as soon as we embrace ANY PHP 7 feature in the upcoming releases.
- We will have an ecosystem of extensions which virtually all will support (and even require PHP7) and therefore Contao will not be usable under PHP 5 anyway.
- Symfony packages are moving to PHP 7 and do not look back, therefore all bundles we need in Contao wont be installable in a recent patch level before long.
- We will not be able to fix security issues introduced by third party libraries because we can not bump to the next minor (then the only supported version by them) by simply bumping the requirement but will end up by forking that repo and hotfix ourselves.

I want to stress this out again, it simply makes no sense to keep this requirement as it is only a burden to us and 5.X will not be usable (due to dependencies) sooner than later.

**Comment by bytehead** [comment]
I totally agree with @discordier and @Toflar on this. 
Extension/Bundle developers for Contao 4 also get forced to update their extensions to be compatible with PHP 7.

**Comment by aschempp** [comment]
Good point. Which means all extensions for Contao 3.5 that are not PHP7 compatible can't be used with the LTS version. Not good imho.

**Comment by discordier** [comment]
> Which means all extensions for Contao 3.5 that are not PHP7 compatible can't be used with the LTS version. Not good imho.

You do not want to open up that case now, do you?

1. Extensions that are currently not compatible with PHP7 will crash in both versions, Contao 3.5 and 4.X when using PHP 7 anyway (as they are likely to use the `String` class or do not know the call convention changes and the like).
Therefore this is rather a argument to drop PHP5 instead of an argument for keeping PHP5.
You will allow them to install under PHP 7 but they will crash.

2. Developers already have to adjust their extensions to make them Contao 4 compatible (adjusting `composer.json` at least), why shouldn't they hvae a look at support with PHP 7 at the same time?

3. They can support both versions of PHP at the same time just like they do with the Contao versions, in fact, they will most likely already support both version as they most likely put `"php": ">=5.3"` in the `composer.json` from the beginning.

It simply makes no sense to try to keep the previous way of "well, the extension is not up to date, unmaintained but it might still work" we had in the ER2. Stuff not marked as compatible is per definition incompatible, so yes, unaltered extensions for C3.5 ARE incompatible with 4.4 until they are MARKED to be compatible.

I reemphase, we should urge people to upgrade and embrace current versions if they want to be compatible with recent versions. PHP is the fundamental basis we build everything upon and therefore should place our minimum requirements to what is available now and will be available during (most of) our support frame.
This clearly disqualifies PHP 5 and could already disqualify PHP 7.0 (EOL 3 Dec 2017).

**Comment by DanielSchwiperich** [comment]
And just raising the composer requirement doesn't make contao not work on php5 Systems as long as we are not using php7 stuff. 
It's just not officially supported any longer.

**Comment by leofeyer** [comment]
Apparently Strato forces all customers to switch to PHP 7 as of February 21st, 2017. Can anyone confirm this?

**Comment by fritzmg** [comment]
PHP 5.6 will still be available, but any customer that is running a lower version than 5.6 will be switched to PHP 7 as far as I understood it.

**Comment by leofeyer** [comment]
Ok, then I'll guess we'll follow @aschempp's [suggestion](https://github.com/contao/core-bundle/issues/701#issuecomment-277715991):

* Contao 4.4 supports PHP 5.6 (but not 5.5)
* Contao 4.5 no longer supports PHP 5.6 (but only PHP 7)

We still need to discuss whether we want `>=7.0.0` or `>=7.1.0` then.

**Comment by leofeyer** [comment]
I have raised the minimum PHP version for Contao 4.4 in f51a70211f05dd6573068aff697feb80aee6b953. This will effectively decrease the number of compatibility layers and we will benefit from the enhanced security and new language constructs.

**Comment by sleitz** [comment]
By the way: Zend Framwork will [move to 7.1](https://framework.zend.com/blog/2017-06-06-zf-php-7-1.html) soon. So there are other who try to be radical as well…

**Comment by Toflar** [comment]
Symfony 4 will go for 7.1 too, to me there's not much to discuss about :)

**Comment by leofeyer** [comment]
Also, the deed is done. See 1cdde8a65806c86052785ca5bf88bdee9a1f93ec.
