### ISSUE TITLE
Filter and Search not working in article module

### ISSUE THREAD

**Issue by agoat** [contao/core-bundle#716]
The Filter and Search function in the article list returns false results.

Can be reproduced in the demo:
- Login
- Open the article list (Content > Articles)
- Choose to filter by 'Display in' and apply

If the filter is set to e.g. show only the articles in the 'Header' column, there will be also returned some articles from the 'Main column':

![false-filter](https://cloud.githubusercontent.com/assets/1402434/23506142/04a4c1d4-ff47-11e6-96fc-d7233d3ed843.jpg)

This also happens in some cases if using the search:

![false-search](https://cloud.githubusercontent.com/assets/1402434/23506258/a7ca8c68-ff47-11e6-825a-522b6e49e07e.jpg)

I have not been further investigating why this is happening.

**Comment by fritzmg** [comment]
The filter only seems to filter the pages. So when you choose _Display in_ » _Header_, it will only show the pages, where there are articles which are displayed in the _Header_, but it will still show all articles from that page. Same with the search.

Also I might add, that I find the filter buttons a little confusing ;). I would expect the "Apply filter" button to somehow "add" a filter 😉 . Imho this should be be a filter icon with a checkmark ✔️ , instead of a ➕ . Also the clickable area of these buttons is rather narrow.

**Comment by leofeyer** [comment]
Fixed in 54c7ed707e2841ef059c2615b5b25645c45803ff.
