### ISSUE TITLE
New dcaPicker: Limit tab items

### ISSUE THREAD

**Issue by daniel-nemeth** [contao/core-bundle#924]
Hi,
is it currently possible to limit the tabs of the new dca picker?
If not it would be nice to have a feature like this.

As example to create a field with dcaPicker=>true and limit the possible tabs to "news" and "events"  instead of showing all tabs.

Thanks and great job!

**Comment by Toflar** [comment]
You cannot limit the tabs. We discussed that and we do not think this makes sense because the picker is extensible and every developer can add their own tabs which you would then need to explicitly allow in **every single DCA configuration** where that picker is being used. That would be a nightmare to maintain 😄  That's why there is the concept of the `context`. There are basically three contexts: `link`, `file` and `page`. Depending on the context, not all of the tabs are shown. E.g. if you choose `file`, you won't have news and events because they make no sense for file selection.

Just pass `'dcaPicker' => ['context' => 'file']` to test that.

**Comment by daniel-nemeth** [comment]
Thanks toflar for your answer!
Is it possible to extend the context with a new type or do we have then the same problem mentioned above?

**Comment by fritzmg** [comment]
> You cannot limit the tabs. We discussed that and we do not think this makes sense because the picker is extensible and every developer can add their own tabs which you would then need to explicitly allow in every single DCA configuration where that picker is being used. That would be a nightmare to maintain

Contexts are fine - but I do not understand that reasoning. If you want to limit your picker to only News articles for example, why would you care about the extensibility of the picker?

**Comment by leofeyer** [comment]
If you don't grant access to anything but news and events, there will be only those two tabs.

**Comment by fritzmg** [comment]
Of course - but I meant what if I want to create a widget, where I specifically only want news to be picked. The editor has access to events as well general, but I do not want him to be able to pick events or anything else but news for that widget.

**Comment by aschempp** [comment]
You would probably need to define your own context and implement a picker for it.

**Comment by daniel-nemeth** [comment]
Is assigning a new context as easy as it looks? Just add a context==='newtype' in the Menu class and then add it to DCA: dcaPicker=>array('context'=>'newtype') ??

**Comment by aschempp** [comment]
you also need one or multiple providers that support the context.

@contao/developers we might want to support context *link_news* to pick just a news items etc.

**Comment by Toflar** [comment]
> it would be fairly simple to define allowed providers with my PR #950 as they now have names/aliases.

That would be best, imho.

**Comment by aschempp** [comment]
This is now supported in #950

**Comment by leofeyer** [comment]
Great, thank you @aschempp.

**Comment by daniel-nemeth** [comment]
Big thanks and good job guys!
