### ISSUE TITLE
BE_USER_LOGGED_IN is not true in Frontend template and logged in BA user

### ISSUE THREAD

**Issue by websolutions-hamburg** [contao/core-bundle#967]
The variable `BE_USER_LOGGED_IN` is not true if a Backend user is logged in. I tested and need it in a Frontend template.

Is this an intended and normal behavior?

I found a working solution for me with `$this->hasAuthenticatedBackendUser()`. But I think the behavior for this variable is wrong.

**Comment by leofeyer** [comment]
That's because the project has grown over time. `BE_USER_LOGGED_IN` used to be `true` if there was a logged in back end user, however, today it will only be `true` in the front end preview if you set "show hidden elements".

Using `$this->hasAuthenticatedBackendUser()` is the correct way of checking if there is an authenticated back end user.
